# Generated by Django 5.0.6 on 2026-06-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_articulo_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
