# Generated by Django 5.0.6 on 2026-06-16 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_venta_monto_efectivo_venta_monto_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='bonificaciones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuentos o bonificaciones que restan del total.', max_digits=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='gastos_varios',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gastos adicionales que suman al total (ej: flete).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.turno'),
        ),
    ]
