"""
Django settings for Doble5 project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Configuración para acceso en red local
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.88.1:8000',
]
# Se recomienda agregar la IP local aquí una vez conocida, ej: 'http://192.168.1.100:8000'


# Application definition

INSTALLED_APPS = [
    'unfold',  # before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Doble5.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Doble5.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": "doble5_db",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'doble5_db',
        'USER': 'doble5_user',
        'PASSWORD': 'password',
        'HOST': 'db',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings
LOGIN_URL = 'admin:login'
LOGIN_REDIRECT_URL = '/turno-grid/'
LOGOUT_REDIRECT_URL = 'admin:login'

# Unfold theme settings
UNFOLD = {
    "SITE_TITLE": "Doble5 Admin",
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": "Navegación Principal",
                "items": [
                    {
                        "title": "Grilla de Turnos",
                        "icon": "calendar_today",
                        "link": "/turno-grid/",
                    },
                    {
                        "title": "Registrar Venta (Bufet)",
                        "icon": "shopping_cart",
                        "link": "/ventas/registrar/",
                    },
{
                        "title": "Registrar Compra (Bufet)",
                        "icon": "shopping_basket",
                        "link": "/compras/registrar/",
                    },
                ],
            },
            {
                "title": "Gestión",
                "separator": True,
                "items": [
                    {
                        "title": "Sedes",
                        "icon": "location_on",
                        "link": "/admin/core/sede/",
                    },
                    {
                        "title": "Canchas",
                        "icon": "sports_soccer",
                        "link": "/admin/core/cancha/",
                    },
                    {
                        "title": "Turnos (Admin)",
                        "icon": "event",
                        "link": "/admin/core/turno/",
                    },
                    {
                        "title": "Cajas",
                        "icon": "account_balance_wallet",
                        "link": "/admin/core/caja/",
                    },
                    {
                        "title": "Notificaciones",
                        "icon": "notifications",
                        "link": "/admin/core/notificacion/",
                    },
                ],
            },
            {
                "title": "Reportes (Admin)",
                "separator": True,
                "items": [
                    {
                        "title": "Reporte Diario",
                        "icon": "assessment",
                        "link": "/reportes/diario/",
                    },
                    {
                        "title": "Reporte Mensual",
                        "icon": "insert_chart",
                        "link": "/reportes/mensual/",
                    },
                ],
            },
            {
                "title": "Bufet (Admin)",
                "separator": True,
                "items": [
                    {
                        "title": "Artículos",
                        "icon": "inventory",
                        "link": "/admin/core/articulo/",
                    },
                    {
                        "title": "Proveedores",
                        "icon": "local_shipping",
                        "link": "/admin/core/proveedor/",
                    },
                    {
                        "title": "Ventas",
                        "icon": "shopping_cart",
                        "link": "/admin/core/venta/",
                    },
                    {
                        "title": "Compras",
                        "icon": "shopping_basket",
                        "link": "/admin/core/compra/",
                    },
                ],
            },
            {
                "title": "Usuarios",
                "separator": True,
                "items": [
                    {
                        "title": "Gestionar Usuarios",
                        "icon": "people",
                        "link": "/admin/auth/user/",
                    },
                ],
            },
        ],
    },
}
